### ISSUE TITLE
Installation Fail

### ISSUE THREAD

**Issue by tolgahanuzun** [emre/lightsteem#1]
There is a problem with the installation via the MacOS operating system.
I guess it's not upload in `pypi`. https://pypi.org/search/?q=lightsteem

![screenshot](https://user-images.githubusercontent.com/10615529/43602672-4fd64278-9699-11e8-90c7-f18604135a8f.png)

**Comment by emre** [comment]
Yeah, it's not uploaded, yet. :) Let's upload it.

**Comment by emre** [comment]
Done. It's accessible on PYPI, now.
